/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_velocitypowered_natives_encryption_OpenSslCipherImpl */

#ifndef _Included_com_velocitypowered_natives_encryption_OpenSslCipherImpl
#define _Included_com_velocitypowered_natives_encryption_OpenSslCipherImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_velocitypowered_natives_encryption_OpenSslCipherImpl
 * Method:    init
 * Signature: ([BZ)J
 */
JNIEXPORT jlong JNICALL Java_com_velocitypowered_natives_encryption_OpenSslCipherImpl_init
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     com_velocitypowered_natives_encryption_OpenSslCipherImpl
 * Method:    process
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_com_velocitypowered_natives_encryption_OpenSslCipherImpl_process
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     com_velocitypowered_natives_encryption_OpenSslCipherImpl
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_velocitypowered_natives_encryption_OpenSslCipherImpl_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
