/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_velocitypowered_natives_compression_NativeZlibInflate */

#ifndef _Included_com_velocitypowered_natives_compression_NativeZlibInflate
#define _Included_com_velocitypowered_natives_compression_NativeZlibInflate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_velocitypowered_natives_compression_NativeZlibInflate
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_velocitypowered_natives_compression_NativeZlibInflate_init
  (JNIEnv *, jclass);

/*
 * Class:     com_velocitypowered_natives_compression_NativeZlibInflate
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_velocitypowered_natives_compression_NativeZlibInflate_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_velocitypowered_natives_compression_NativeZlibInflate
 * Method:    process
 * Signature: (JJIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_velocitypowered_natives_compression_NativeZlibInflate_process
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
